In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import curve_fit
from sklearn.metrics import mean_absolute_error

In [2]:
dati = pd.read_csv('bitcoin_data_28-4-2013_4-3-2024_granularità_1_giorno.csv')
dati

Timestamp     Price (€)
0     2013-04-28 00:00:00.000    103.186200
1     2013-04-29 00:00:00.000    110.374500
2     2013-04-30 00:00:00.000    106.312800
3     2013-05-01 00:00:00.000     88.629100
4     2013-05-02 00:00:00.000     80.592300
...                       ...           ...
3957  2024-02-29 00:00:00.000  57717.736389
3958  2024-03-01 00:00:00.000  56734.564616
3959  2024-03-02 00:00:00.000  57560.483900
3960  2024-03-03 00:00:00.000  57229.676585
3961  2024-03-04 00:00:00.000  58157.094855

[3962 rows x 2 columns]

### Curve_fit

In [46]:
# Contatore globale
eval_count = 0

# Legge da fittare: y = A * x^B
def legge(x, A, B, C, D, E, F):
    global eval_count
    eval_count += 1
    return A * x**B + C * np.sin(D*x + E) + F

# Creiamo un array per l'asse x (tempo o indice dei prezzi)
x = np.arange(1, len(dati) + 1)
y = dati['Price (€)'].values

# Ottimizzazione dei parametri
try:
    # curve_fit cerca i migliori parametri A e B
    popt, pcov = curve_fit(legge, x, y, p0=[1, 1, 1, 1, 1, 0], maxfev=10000)

    # Generazione dei valori predetti
    y_pred = legge(x, *popt)

    # Calcolo degli errori
    mae = mean_absolute_error(y, y_pred)
    mape = np.mean(np.abs((y - y_pred) / y)) * 100

    print(f"Parametri ottimizzati: {popt}")
    print(f"MAE: {mae}")
    print(f"MAPE: {mape}%")
    print(f"Numero di valutazioni della funzione: {eval_count}")

except RuntimeError as e:
    print("Errore nell'ottimizzazione:", e)

Parametri ottimizzati: [ 4.54751661e-03  1.92959282e+00  2.94437752e+01  9.97093830e-01
 -1.27923201e+01 -1.78820149e+03]
MAE: 5359.841786647315
MAPE: 234.73707941722188%
Numero di valutazioni della funzione: 324


In [47]:
pcov

array([[ 3.85425086e-06, -1.02818258e-04,  1.65466477e-04,
        -1.07061874e-08,  9.25224685e-06, -4.44139248e-01],
       [-1.02818258e-04,  2.74454381e-03, -4.28154896e-03,
         2.97210657e-07, -2.64182649e-04,  1.16640543e+01],
       [ 1.65466477e-04, -4.28154896e-03,  3.29326561e+04,
         5.83516071e-06, -3.02750114e-01, -3.99194273e+01],
       [-1.07061874e-08,  2.97210657e-07,  5.83516071e-06,
         2.90948007e-05, -5.76529157e-02,  2.80914444e-04],
       [ 9.25224685e-06, -2.64182649e-04, -3.02750114e-01,
        -5.76529157e-02,  1.52290467e+02,  5.93492996e-01],
       [-4.44139248e-01,  1.16640543e+01, -3.99194273e+01,
         2.80914444e-04,  5.93492996e-01,  8.75354767e+04]])

### Minimize

In [57]:
from scipy.optimize import minimize
import numpy as np
from sklearn.metrics import mean_absolute_error

# Funzione di errore con regolarizzazione
def loss(params, x, y, lambda_reg):
    A, B, C, D, E, F = params
    y_pred = A * x**B + C * np.sin(D * x + E) + F
    mse = np.mean((y - y_pred)**2)
    reg = lambda_reg * (F**2)  # Penalizzazione
    return mse + reg

# Ottimizzazione
initial_params = [1, 1, 1, 1, 1, 1]
result = minimize(loss, initial_params, args=(x, y, 0.01))  # lambda_reg=0.01

# Parametri ottimizzati
optimized_params = result.x
A, B, C, D, E, F = optimized_params

# Calcolo dei valori predetti
y_pred = A * x**B + C * np.sin(D * x + E) + F

# Calcolo MAE
mae = mean_absolute_error(y, y_pred)

# Calcolo MAPE
mape = np.mean(np.abs((y - y_pred) / y)) * 100

# Numero di valutazioni della funzione
n_evaluations = result.nfev

print(f"MAE: {mae}")
print(f"MAPE: {mape}%")
print(f"Numero di valutazioni della funzione: {n_evaluations}")

MAE: 5351.342789654394
MAPE: 228.69943966435477%
Numero di valutazioni della funzione: 1895


In [58]:
optimized_params

array([ 4.22160214e-03,  1.93841250e+00, -2.32314951e+01,  7.89011201e-01,
        4.36347449e+02, -1.71359330e+03])

In [59]:
result

  message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: 65181055.29958218
        x: [ 4.222e-03  1.938e+00 -2.323e+01  7.890e-01  4.363e+02
            -1.714e+03]
      nit: 169
      jac: [-2.059e+05 -1.098e+04  5.000e-01 -4.233e+04 -7.000e+00
            -1.500e+00]
 hess_inv: [[ 3.658e-11 -1.072e-09 ...  5.480e-07  9.438e-08]
            [-1.072e-09  3.145e-08 ... -1.607e-05 -2.796e-06]
            ...
            [ 5.480e-07 -1.607e-05 ...  1.934e-02 -2.021e-03]
            [ 9.438e-08 -2.796e-06 ... -2.021e-03  5.910e-03]]
     nfev: 1895
     njev: 269

### Reti neurali

In [3]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [9]:
# Funzione per creare e compilare il modello
def create_model(input_shape, width, depth, activation, loss):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.InputLayer(input_shape=(input_shape,)))
    for _ in range(depth):
        model.add(tf.keras.layers.Dense(width, activation=activation))
    model.add(tf.keras.layers.Dense(1))  # Uscita singola per la previsione del prezzo
    model.compile(optimizer=tf.keras.optimizers.Adam(), loss=loss)
    return model

# Funzione per dividere i dati in train, validation e test
def split_data(x, y, train_size=0.7, val_size=0.15, test_size=0.15):
    x_train, x_temp, y_train, y_temp = train_test_split(x, y, train_size=train_size, random_state=42, shuffle=False)
    val_ratio = val_size / (val_size + test_size)
    x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, train_size=val_ratio, random_state=42, shuffle=False)
    return x_train, x_val, x_test, y_train, y_val, y_test

# Funzione per allenare il modello
def train_model(model, x_train, y_train, x_val, y_val, patience=10, epochs=100, batch_size=32):
    early_stopping = tf.keras.callbacks.EarlyStopping(
        monitor='val_loss', patience=patience, restore_best_weights=True
    )
    history = model.fit(
        x_train, y_train,
        validation_data=(x_val, y_val),
        epochs=epochs,
        callbacks=[early_stopping],
        batch_size=batch_size,
        verbose=2
    )
    return history

# Funzione per valutare il modello
def evaluate_model(model, x, y):
    y_pred = model.predict(x).flatten()
    mae = mean_absolute_error(y, y_pred)
    mape = np.mean(np.abs((y - y_pred) / y)) * 100
    return mae, mape

# Funzione principale
def main(data, train_size=0.7, val_size=0.15, test_size=0.15, width=64, depth=3, patience=10, epochs=100, batch_size=32, activation='relu', loss='mse'):
    # Prepara i dati
    x = np.arange(1, len(data) + 1).reshape(-1, 1)  # Indici come input
    y = data['Price (€)'].values  # Prezzi come target

    x_train, x_val, x_test, y_train, y_val, y_test = split_data(x, y, train_size, val_size, test_size)

    # Crea il modello
    model = create_model(input_shape=x_train.shape[1], width=width, depth=depth, activation=activation, loss=loss)

    # Allena il modello
    print("Training the model...")
    train_model(model, x_train, y_train, x_val, y_val, patience=patience, epochs=epochs, batch_size=batch_size)

    # Valuta il modello
    print("Evaluating the model...")
    train_mae, train_mape = evaluate_model(model, x_train, y_train)
    val_mae, val_mape = evaluate_model(model, x_val, y_val)
    test_mae, test_mape = evaluate_model(model, x_test, y_test)

    # Risultati
    print(f"Train MAE: {train_mae}, Train MAPE: {train_mape}%")
    print(f"Validation MAE: {val_mae}, Validation MAPE: {val_mape}%")
    print(f"Test MAE: {test_mae}, Test MAPE: {test_mape}%")

In [10]:
main(dati, train_size=0.7, val_size=0.15, test_size=0.15, width=1024, depth=5, patience=10, epochs=1000, batch_size=32, activation='sigmoid', loss='mape')

Training the model...
Epoch 1/1000


c:\Users\Alessandro\Desktop\Cartelle\Mie\Programmi personali in Python\Kaggle\Bitcoin Historical Dataset\trading_env\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


87/87 - 7s - 77ms/step - loss: 90.4672 - val_loss: 99.7955
Epoch 2/1000
87/87 - 4s - 42ms/step - loss: 82.5879 - val_loss: 99.6999
Epoch 3/1000
87/87 - 4s - 42ms/step - loss: 80.3860 - val_loss: 99.6371
Epoch 4/1000
87/87 - 4s - 44ms/step - loss: 79.0749 - val_loss: 99.5741
Epoch 5/1000
87/87 - 4s - 42ms/step - loss: 77.8595 - val_loss: 99.5124
Epoch 6/1000
87/87 - 4s - 42ms/step - loss: 76.6565 - val_loss: 99.4464
Epoch 7/1000
87/87 - 4s - 42ms/step - loss: 75.5384 - val_loss: 99.3850
Epoch 8/1000
87/87 - 4s - 42ms/step - loss: 75.0042 - val_loss: 99.3608
Epoch 9/1000
87/87 - 4s - 43ms/step - loss: 74.9422 - val_loss: 99.3561
Epoch 10/1000
87/87 - 4s - 42ms/step - loss: 74.9517 - val_loss: 99.3505
Epoch 11/1000
87/87 - 4s - 43ms/step - loss: 74.9343 - val_loss: 99.3508
Epoch 12/1000
87/87 - 4s - 43ms/step - loss: 74.9412 - val_loss: 99.3487
Epoch 13/1000
87/87 - 4s - 42ms/step - loss: 74.9367 - val_loss: 99.3520
Epoch 14/1000
87/87 - 4s - 44ms/step - loss: 74.9455 - val_loss: 99.3483
